In [1]:
import pandas as pd
import numpy as np
import sklearn
from sklearn import datasets

In [2]:
df = pd.read_csv('Heart_Disease_Prediction.csv')

In [3]:
df.describe()

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium
count,270.000000,270.000000,270.000000,270.000000,270.000000,270.000000,270.000000,270.000000,270.000000,270.00000,270.000000,270.000000,270.000000
mean,54.433333,0.677778,3.174074,131.344444,249.659259,0.148148,1.022222,149.677778,0.329630,1.05000,1.585185,0.670370,4.696296
std,9.109067,0.468195,0.950090,17.861608,51.686237,0.355906,0.997891,23.165717,0.470952,1.14521,0.614390,0.943896,1.940659
min,29.000000,0.000000,1.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.00000,1.000000,0.000000,3.000000
25%,48.000000,0.000000,3.000000,120.000000,213.000000,0.000000,0.000000,133.000000,0.000000,0.00000,1.000000,0.000000,3.000000
50%,55.000000,1.000000,3.000000,130.000000,245.000000,0.000000,2.000000,153.500000,0.000000,0.80000,2.000000,0.000000,3.000000
75%,61.000000,1.000000,4.000000,140.000000,280.000000,0.000000,2.000000,166.000000,1.000000,1.60000,2.000000,1.000000,7.000000
max,77.000000,1.000000,4.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.20000,3.000000,3.000000,7.000000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270 entries, 0 to 269
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      270 non-null    int64
 1   Sex                      270 non-null    int64
 2   Chest pain type          270 non-null    int64
 3   BP                       270 non-null    int64
 4   Cholesterol              270 non-null    int64
 5   FBS over 120             270 non-null    int64
 6   EKG results              270 non-null    int64
 7   Max HR                   270 non-null    int64
 8   Exercise angina          270 non-null    int64
 9   ST depression            270 non-null    float64
 10  Slope of ST              270 non-null    int64
 11  Number of vessels fluro  270 non-null    int64
 12  Thallium                 270 non-null    int64
 13  Heart Disease            270 non-null    object
dtypes: float64(1), int64(12), object(1)
memory usage: 29.7+ KB

In [5]:
df.tail()

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
265,52,1,3,172,199,1,0,162,0,0.5,1,0,7,Absence
266,44,1,2,120,263,0,0,173,0,0.0,1,0,7,Absence
267,56,0,2,140,294,0,2,153,0,1.3,2,0,3,Absence
268,57,1,4,140,192,0,0,148,0,0.4,2,0,6,Absence
269,67,1,4,160,286,0,2,108,1,1.5,2,3,3,Presence

In [6]:
df.head()

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
0,70,1,4,130,322,0,2,109,0,2.4,2,3,3,Presence
1,67,0,3,115,564,0,2,160,0,1.6,2,0,7,Absence
2,57,1,2,124,261,0,0,141,0,0.3,1,0,7,Presence
3,64,1,4,128,263,0,0,105,1,0.2,2,1,7,Absence
4,74,0,2,120,269,0,2,121,1,0.2,1,1,3,Absence

In [8]:
del df['Heart Disease']

In [10]:
df.median()

Age                         55.0
Sex                          1.0
Chest pain type              3.0
BP                         130.0
Cholesterol                245.0
FBS over 120                 0.0
EKG results                  2.0
Max HR                     153.5
Exercise angina              0.0
ST depression                0.8
Slope of ST                  2.0
Number of vessels fluro      0.0
Thallium                     3.0
dtype: float64

In [11]:
df.mean()

Age                         54.433333
Sex                          0.677778
Chest pain type              3.174074
BP                         131.344444
Cholesterol                249.659259
FBS over 120                 0.148148
EKG results                  1.022222
Max HR                     149.677778
Exercise angina              0.329630
ST depression                1.050000
Slope of ST                  1.585185
Number of vessels fluro      0.670370
Thallium                     4.696296
dtype: float64

In [12]:
df.Age.mode

<bound method Series.mode of 0      70
1      67
2      57
3      64
4      74
       ..
265    52
266    44
267    56
268    57
269    67
Name: Age, Length: 270, dtype: int64>

In [13]:
df.groupby(['BP']).count()

,Age,Sex,Chest pain type,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium
BP,,,,,,,,,,,,
94,2,2,2,2,2,2,2,2,2,2,2,2
100,4,4,4,4,4,4,4,4,4,4,4,4
101,1,1,1,1,1,1,1,1,1,1,1,1
102,2,2,2,2,2,2,2,2,2,2,2,2
104,1,1,1,1,1,1,1,1,1,1,1,1
105,3,3,3,3,3,3,3,3,3,3,3,3
106,1,1,1,1,1,1,1,1,1,1,1,1
108,6,6,6,6,6,6,6,6,6,6,6,6
110,17,17,17,17,17,17,17,17,17,17,17,17
112,9,9,9,9,9,9,9,9,9,9,9,9
115,3,3,3,3,3,3,3,3,3,3,3,3
117,1,1,1,1,1,1,1,1,1,1,1,1
118,7,7,7,7,7,7,7,7,7,7,7,7
120,34,34,34,34,34,34,34,34,34,34,34,34
122,3,3,3,3,3,3,3,3,3,3,3,3
123,1,1,1,1,1,1,1,1,1,1,1,1
124,5,5,5,5,5,5,5,5,5,5,5,5
125,10,10,10,10,10,10,10,10,10,10,10,10
126,3,3,3,3,3,3,3,3,3,3,3,3
128,9,9,9,9,9,9,9,9,9,9,9,9
129,1,1,1,1,1,1,1,1,1,1,1,1
130,31,31,31,31,31,31,31,31,31,31,31,31
132,6,6,6,6,6,6,6,6,6,6,6,6
134,4,4,4,4,4,4,4,4,4,4,4,4
135,6,6,6,6,6,6,6,6,6,6,6,6
136,3,3,3,3,3,3,3,3,3,3,3,3
138,9,9,9,9,9,9,9,9,9,9,9,9
140,30,30,30,30,30,30,30,30,30,30,30,30
142,3,3,3,3,3,3,3,3,3,3,3,3
144,1,1,1,1,1,1,1,1,1,1,1,1
145,5,5,5,5,5,5,5,5,5,5,5,5
146,1,1,1,1,1,1,1,1,1,1,1,1
148,1,1,1,1,1,1,1,1,1,1,1,1
150,17,17,17,17,17,17,17,17,17,17,17,17
152,4,4,4,4,4,4,4,4,4,4,4,4
155,1,1,1,1,1,1,1,1,1,1,1,1
156,1,1,1,1,1,1,1,1,1,1,1,1
158,1,1,1,1,1,1,1,1,1,1,1,1
160,11,11,11,11,11,11,11,11,11,11,11,11
165,1,1,1,1,1,1,1,1,1,1,1,1
170,2,2,2,2,2,2,2,2,2,2,2,2
172,1,1,1,1,1,1,1,1,1,1,1,1
174,1,1,1,1,1,1,1,1,1,1,1,1
178,2,2,2,2,2,2,2,2,2,2,2,2
180,3,3,3,3,3,3,3,3,3,3,3,3
192,1,1,1,1,1,1,1,1,1,1,1,1
200,1,1,1,1,1,1,1,1,1,1,1,1

In [14]:
df.Age.std()

9.109066523898203